### ISSUE TITLE
Pipeseroni's Wishlist

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipeseroni.github.io#1]
This is a follow-up of pipeseroni/pipes.sh#14. As I (@livibetter) stated, I'd not do the following tasks since I want to have people join and contribute.

This [pipeseroni.github.io](https://github.com/pipeseroni/pipeseroni.github.io) would be the webpage and for the issue directly concerning this organization.

If you want to join or discuss, please feel free to create an issue, I will link them here. Or, you can directly create pull requests if you believe no discussions is necessary.
- [x] avatar/icon/logo for GitHub account or else. (#tbd, see also [this comment](https://github.com/pipeseroni/pipes.sh/issues/14#issuecomment-94710799))
- [x] `gh-pages` (#tbd)
  
  This webpage have to link to all projects under @pipeseroni. Simple one-page would do, perhaps utilizing GitHub API to query all the project to avoid the need to manual updates.

**Comment by livibetter** [comment]
I stumbled across @joshdk's [maze](https://github.com/joshdk/maze), would it be a good addition to @pipeseroni?

**Comment by livibetter** [comment]
Just discovered this Python implementation @gardaud's [pipes](https://github.com/gardaud/pipes).

---
- I'm going to close this since I wasn't maintaining anymore, and this probably would be the last involvement, for real. Please do not reopen, don't want this to show up in my Issues list.
- @Foggalong I noticed you ain't on repository's Watcher list, not sure if you'll be getting any notification regarding this repository, hopefully this ping would get to you.

**Comment by Foggalong** [comment]
Thanks for the ping :) I've been incredibly busy with work over the last few weeks but this weekend I'll have a bitnmore free time to spend on pipeseroni. Gonna set up the website, get a logo done, etc.

I'll look into that Python version. There was another one which I contacted about joining but they never replied. I'll try this one too

**Comment by livibetter** [comment]
Just found @gonmf / [tubes](https://github.com/gonmf/tubes). I think I will just leave a comment here every times I see something like a few bendable lines.

**Comment by ghost** [comment]
Just saw the comment from July 10th mentioning my repo, thanks! :)

Pull requests are happily requested. I've had a few fixes/tweaks for it planned for a while, this minor signaling of interest might be the impulse I need to finally write them :)

**Comment by Foggalong** [comment]
Awesome :D
