### ISSUE TITLE
@Foggalong as Admin

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipeseroni.github.io#2]
After some considerations, I'd like to bring @Foggalong on board as an Admin, a few things:
1. In case of other admins gone AWOL.
   
   Less than a year ago, I handed over an organization to someone I trusted would handle well, but now nothing happened there for months.
   
   I do not want this happen here, so bringing @Foggalong in might avoid if that ever happen, from everywhere I could see, I believe I can trust him.
2. Need someone to post on Reddit for pipeseroni/pipes.sh#13.
   
   I really want to know who wrote the original `pipes.sh`, the question has been in my mind for years ever since I saw the pipes.
3. Perhaps Pipeseroni's Chief of Social Relations
   
   Is that even a real position? Anyway, it just means social stuff would handle by @Foggalong if we ever need to do those, which I am not so sure.

@Foggalong if you are not okay for posting for that question, I am okay with that, but I still want to add you as Admin. Basically, you just sit here and watch everything going by.

Would you accept?

**Comment by Foggalong** [comment]
That is completely fine for me :) Glad to be of help!

**Comment by livibetter** [comment]
@Foggalong Good, invite sent.
