### ISSUE TITLE
Textual logo for terminal

### ISSUE THREAD

**Issue by livibetter** [pipeseroni/pipeseroni.github.io#7]
As you may know that @judavi is working on [Docker](https://github.com/judavi/docker-pipeseroni), and there will be a menu for selecting a pipe to run.  So, I am thinking to have a textual logo that can be used in terminal and that menu.

I wrote two scripts (now in `hq` branch, which would host files like this and `master` continues to have web stuff) to help colorize and generate a set of logos with different ANSI escape code color specs; and three logos (`logo{1..3}.txt` in [logos.txt.tar.gz](https://github.com/pipeseroni/pipeseroni.github.io/files/1889078/logos.txt.tar.gz), which includes all generated text files):

![logos](https://user-images.githubusercontent.com/30909/38488145-0a79e9de-3c15-11e8-81ba-eb6a69377abf.png)
[Left to right: `logo1.txt` | `logo2.txt` | `logo3.txt`]

The logo has a dimension of 20 columns by 10 lines.

Quick summary of the generation process: the `logos-gen.sh` takes a source text and runs `logo-colorize.sh` with different color settings (or escape codes to wrap the chars, if you will).  For spaces, the purple shade is used, and red color for other characters.  (Although `1` and `2` are special case, that made specifically for `logo3.txt`, without `2`, there will be gap` as you can see vertically parallel pipes has a gap/space between them.) All those red ones are actually with same color in foreground and background, the ASCII/Unicode chars are still there.

Personally, I like the result of colorized `logo1.txt`, really close to the [original logo.svg](https://github.com/pipeseroni/pipeseroni.github.io/blob/master/assets/images/logo.svg) by @Foggalong , but I also dislike its `-plain.txt` form, it's borderline acceptable, and it doesn't actually represent `pipes.sh`'s actual output.  Although technically, none of the three does.  This might be just picky since it's a logo.

I'd like some inputs or even new textual logo designs to match the original or tinkering of the scripts/coloros (256 and 16, 24bit has exact colors as the original SVG), but if I get nothing, then I probably would go for `logo1.txt` and commit the generated files, then ask @judavi to use it.  (There will be issues to discuss, which we are going, 24bit is likely not a safe option, but that would be another time)

Please note that any new designs are welcome, and it doesn't have to any generation in use, complete handcraft one is definitely okay, but that's the main reason I wrote the script to simplify things, because I don't know what specialized ANSI text editor to use.  The only important thing is that it must have a color version, and another is plain text without any color codes, also they must look like visually similar to at least like mine above.

----

(Off-topic: This somewhat reminds me of the time of BBS games with *animation*, if anyone wants to go that far for the menu, I am not stopping you.  Hmm, what if we run a telnet server?)

**Comment by StefansM** [comment]
Very nice. I think the best of the colourised logos is from `logo1.txt`. How about using block-drawing characters for `logo1.txt`?

```
                    0
    █████████████   1
    █████████████   2
    ████     ████   3
    ████     ████   4
███ ████ ████████   5
███ ████ ████████   6
    ████            7
    ████            8
    ████            9
00112233445566778899
```

**Comment by StefansM** [comment]
Alternatively, I quite like the combination of `logo3-plain.txt` and the `logo1-*` coloured versions.

**Comment by livibetter** [comment]
@StefansM 

I want to have some spirit of pipes in the logo, visual hints, that's why I ended up writing the scripts, so it could generate colorized-and-Block-Element-like (original-SVG-like) logos and a plain ASCII or Unicode version from a single source.

If nothing comes up better, we can either go for that mix or just have the Block Element one.  I think I'd prefer the Block Element, because I don't actually like `logo3-plain.txt`, even it's better than first two, just not good enough.  2 pipes don't look good -- kind of thin, if that makes sense -- but with terminal graphics, that's the best I can draw, I think 3 or 4 would look out of proportion.

Besides, as now I see it, the original SVG is one big thick pipe, so using Block Element should be the way to do it.

----

```bash
alias blockpipes='./pipes.sh -t c████████████████'
blockpipes -p 3 -c 1 -c 2 -c 4 -r 0
```

![2018-04-11--22 40 29](https://user-images.githubusercontent.com/30909/38623959-876abd04-3dd9-11e8-925e-c1428cb3a876.png)
